/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javasystemapplication;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

/**
 *
 * @author CarlosGalvan
 */
public class BuscarProducto extends javax.swing.JFrame {

    private JTextField txtBuscar;
    private JTable tablaProductos;
    private DefaultTableModel modeloTabla;
    private JButton btnRegresar;
    private ProductoDAO productoDAO;

    /**
     * Creates new form BuscarProducto
     */
    public BuscarProducto() {
        // Configuración inicial de la ventana
        setTitle("Buscar Producto");
        setSize(600, 400);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());

        // Panel para el campo de búsqueda
        JPanel panelBusqueda = new JPanel();
        panelBusqueda.setLayout(new FlowLayout());
        JLabel lblBuscar = new JLabel("Buscar Producto:");
        txtBuscar = new JTextField(20);
        panelBusqueda.add(lblBuscar);
        panelBusqueda.add(txtBuscar);

        // Configurar la tabla para mostrar los productos
        modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("Nombre Producto");

        tablaProductos = new JTable(modeloTabla);
        JScrollPane scrollPane = new JScrollPane(tablaProductos);

        // Botón para regresar
        btnRegresar = new JButton("Regresar");
        btnRegresar.setBackground(new Color(169, 169, 169));
        btnRegresar.setForeground(Color.WHITE);
        btnRegresar.setFont(new Font("Arial", Font.BOLD, 14));
        btnRegresar.setPreferredSize(new Dimension(120, 40));
        btnRegresar.setFocusPainted(false);

        // Panel para el botón Regresar
        JPanel panelBotonRegresar = new JPanel();
        panelBotonRegresar.add(btnRegresar);

        // Añadir los componentes al JFrame
        add(panelBusqueda, BorderLayout.NORTH);
        add(scrollPane, BorderLayout.CENTER);
        add(panelBotonRegresar, BorderLayout.SOUTH);

        // Añadir el DocumentListener para la búsqueda en tiempo real
        txtBuscar.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                buscarProducto();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                buscarProducto();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                buscarProducto();
            }
        });

        // Acción del botón Regresar
        btnRegresar.addActionListener(e -> {
            dispose();
            new PantallaProductos().setVisible(true); // Regresa a la pantalla de productos
        });

        // Cargar los productos al iniciar
        productoDAO = new ProductoDAO();
        cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarProducto().setVisible(true);
            }
        });
    }

    // Método para cargar productos desde la base de datos
    private void cargarProductos() {

        List<String> productos = productoDAO.obtenerProductos();

        // Limpiar la tabla antes de cargar nuevos productos
        modeloTabla.setRowCount(0);

        // Llenar la tabla con los productos obtenidos
        for (String producto : productos) {
            modeloTabla.addRow(new Object[]{producto});
        }
    }

    // Método para buscar productos en tiempo real
    private void buscarProducto() {
        String textoBusqueda = txtBuscar.getText().trim().toLowerCase();

        // Si el campo de búsqueda está vacío, mostramos todos los productos
        if (textoBusqueda.isEmpty()) {
            cargarProductos();
        } else {
            List<String> productos = ProductoDAO.buscarProductos(textoBusqueda);

            // Limpiar la tabla antes de cargar los resultados
            modeloTabla.setRowCount(0);

            // Llenar la tabla con los productos encontrados
            for (String producto : productos) {
                modeloTabla.addRow(new Object[]{producto});
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
