/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javasystemapplication;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author CarlosGalvan
 */
public class EditarCliente extends javax.swing.JFrame {

    private JTextField txtNombreCliente, txtDomicilio, txtRFC;
    private JButton btnGuardar, btnCancelar;
    private String idCliente;
    private PantallaClientes parent;

    /**
     * Creates new form EditarCliente
     */
 public EditarCliente(String id, String nombreCliente, String domicilio, String rfc, PantallaClientes parent) {
        this.idCliente = id;
        this.parent = parent;

        setTitle("Editar Cliente");
        setSize(400, 300);
        setLocationRelativeTo(parent);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(new GridLayout(4, 2));

        // Campos de texto
        JLabel lblNombreCliente = new JLabel("Nombre Cliente:");
        txtNombreCliente = new JTextField(nombreCliente);

        JLabel lblDomicilio = new JLabel("Domicilio:");
        txtDomicilio = new JTextField(domicilio);

        JLabel lblRFC = new JLabel("RFC:");
        txtRFC = new JTextField(rfc);

        // Botones
        btnGuardar = new JButton("Guardar");
        btnCancelar = new JButton("Cancelar");

        // Agregar componentes
        add(lblNombreCliente);
        add(txtNombreCliente);
        add(lblDomicilio);
        add(txtDomicilio);
        add(lblRFC);
        add(txtRFC);
        add(btnGuardar);
        add(btnCancelar);

        // Estilos de botones
        btnGuardar.setBackground(new Color(0, 102, 204));
        btnGuardar.setForeground(Color.WHITE);
        btnCancelar.setBackground(Color.GRAY);
        btnCancelar.setForeground(Color.WHITE);

        // Eventos de los botones
        btnGuardar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String nombreCliente = txtNombreCliente.getText().trim();
                String domicilio = txtDomicilio.getText().trim();
                String rfc = txtRFC.getText().trim();

                if (nombreCliente.isEmpty() || domicilio.isEmpty() || rfc.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                int confirmacion = JOptionPane.showConfirmDialog(null, 
                        "¿Deseas guardar los cambios?\n\nNombre: " + nombreCliente + "\nDomicilio: " + domicilio + "\nRFC: " + rfc, 
                        "Confirmar Edición", JOptionPane.YES_NO_OPTION);

                if (confirmacion == JOptionPane.YES_OPTION) {
                    if (new ClienteDAO().editarCliente(idCliente, nombreCliente, domicilio, rfc)) {
                        JOptionPane.showMessageDialog(null, "Cliente actualizado correctamente.");
                        parent.cargarClientes(); // Actualizar tabla en la pantalla principal
                        dispose(); // Cerrar ventana de edición
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al actualizar el cliente.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });

        btnCancelar.addActionListener(e -> dispose());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarCliente(null, null, null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
