/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javasystemapplication;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

/**
 *
 * @author CarlosGalvan
 */
public class PantallaProductos extends javax.swing.JFrame {

    private JTable tablaProductos;
    private DefaultTableModel modeloTabla;
    private JButton btnAgregar, btnAlta, btnBaja, btnBuscar, btnEditar, btnEliminar, btnRegresar;

    /**
     * Creates new form PantallaProductos
     */
    public PantallaProductos() {
        setTitle("Gestión de Productos");
        setSize(800, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());

        // 🔹 Modelo de tabla
        modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("Nombre Producto");
        modeloTabla.addColumn("Unidad");
        modeloTabla.addColumn("Clase");
        modeloTabla.addColumn("Lote");

        // 🔹 Tabla con scroll
        tablaProductos = new JTable(modeloTabla);
        JScrollPane scrollPane = new JScrollPane(tablaProductos);

        // 🔹 Panel superior (Alta y Baja)
        JPanel panelSuperior = new JPanel(new FlowLayout());
        btnAlta = new JButton("Alta");
        btnBaja = new JButton("Baja");
        panelSuperior.add(btnAlta);
        panelSuperior.add(btnBaja);

        // 🔹 Panel inferior (Agregar, Buscar, Editar, Eliminar, Regresar)
        JPanel panelInferior = new JPanel(new FlowLayout());
        btnAgregar = new JButton("Agregar Producto");
        btnBuscar = new JButton("Buscar");
        btnEditar = new JButton("Editar");
        btnEliminar = new JButton("Eliminar");
        btnRegresar = new JButton("Regresar");

        panelInferior.add(btnAgregar);
        panelInferior.add(btnBuscar);
        panelInferior.add(btnEditar);
        panelInferior.add(btnEliminar);
        panelInferior.add(btnRegresar);

        add(panelSuperior, BorderLayout.NORTH);
        add(scrollPane, BorderLayout.CENTER);
        add(panelInferior, BorderLayout.SOUTH);

        // 🔹 Aplicar estilos a los botones
        aplicarEstilos();

        // 🚀 Espacios listos para eventos de botones
        btnAlta.addActionListener(e -> {
            // Aquí se agregará la funcionalidad para dar de alta un producto
        });

        btnBaja.addActionListener(e -> {
            // Aquí se agregará la funcionalidad para dar de baja un producto
        });

        btnAgregar.addActionListener(e -> {
            // Aquí se agregará la funcionalidad para agregar un producto
        });

        btnBuscar.addActionListener(e -> {
            // Aquí se agregará la funcionalidad para buscar un producto
        });

        btnEditar.addActionListener(e -> {
            // Aquí se agregará la funcionalidad para editar un producto
        });

        btnEliminar.addActionListener(e -> {
            // Aquí se agregará la funcionalidad para eliminar un producto
        });

        btnRegresar.addActionListener(e -> {
            dispose();
            new MenuPrincipal().setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaProductos().setVisible(true);
            }
        });
    }

    // 🔹 Aplicar estilos a los botones
    private void aplicarEstilos() {
        Color azul = new Color(0, 102, 204);
        Color rojo = new Color(204, 0, 0);
        Color gris = Color.GRAY;
        Color blanco = Color.WHITE;

        btnAlta.setBackground(azul);
        btnAlta.setForeground(blanco);
        btnBaja.setBackground(rojo);
        btnBaja.setForeground(blanco);
        btnAgregar.setBackground(azul);
        btnAgregar.setForeground(blanco);
        btnBuscar.setBackground(azul);
        btnBuscar.setForeground(blanco);
        btnEditar.setBackground(azul);
        btnEditar.setForeground(blanco);
        btnEliminar.setBackground(rojo);
        btnEliminar.setForeground(blanco);
        btnRegresar.setBackground(gris);
        btnRegresar.setForeground(blanco);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
